### ISSUE TITLE
Drop autohintexe

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/psautohint#245]
`autohintexe` was added to the wheels (issue #79) to support removing the `autohint` tool out of the AFDKO.

As of version 3.2.0 the AFDKO still includes the `autohint` command, [but it's a simple wrapper of `psautohint`](https://github.com/adobe-type-tools/afdko/blob/develop/NEWS.md#320-released-2020-01-24).

Therefore it's no longer necessary to build `autohintexe` (nor include it in the wheels).

See 6abb616429518687665ad5e5e91c5f1aa5c669c8, and remove the following lines from `.travis.yml`:
```
    - os: linux
      install:
        - pip3 install meson ninja
      script:
        - meson build libpsautohint
        - ninja -C build
        - ls build
        - build/autohintexe -h
      after_success: skip
```
